"use strict";
/*
    Coder: POCH
    File: i18n.js
    Lines:  630
    Date:
    Purpose:i8{}- contains objects containing hindi, marathi,tamil and english words and sentences to use it for translations  . 
*/

let i8 = {
  "hi": {
    "WELCOME_1": "तुबली में आपका स्वागत है",
    "ENTER_USERNAME_2": "अपना उपयोगकर्ता नाम दर्ज करें",
    "ENTER_PASSWORD_3": "अपना पासवर्ड डालें",
    "FIST_NAME_4": "पहला नाम",
    "LAST_NAME_5": "अंतिम नाम",
    "DATE_OF_BIRTH_6": "जन्म की तारीख",
    "CITY_7": "शहर",
    "STATE_8": "राज्य",
    "COUNTRY_9": "देश",
    "SUBMIT_10": "जमा करें",
    "INCORRECT_USERNAME_PASSWORD_11": "ग़लत उपयोगकर्ता नाम / पासवर्ड",
    "CONFIRM_PASSWORD_12": "पासवर्ड की पुष्टि कीजिये",
    "LOGIN_FACEBOOK_13": "फेसबुक में जाये",
    "HELP_14": "मदद",
    "ACCOUNT_15": "लेखा",
    "CHOOSE_GENDER_16": "अपना लिंग चुनें",
    "MALE_17": "नर",
    "FEMALE_18": "महिला",
    "OTHER_19": "अन्य",
    "SETTINGS_20": "सेटिंग्स",
    "UPDATE_PROFILE_21": "प्रोफ़ाइल अपडेट करें",
    "UPLOAD_PHOTO_22": "फोटो अपलोड करें",
    "EDIT_PROFILE_PHOTO_23": "प्रोफ़ाइल फ़ोटो संपादित करें",
    "SET_PROFILE_PHOTO_24": "प्रोफ़ाइल फ़ोटो सेट करें",
    "ABOUT_YOURSELF_25": "अपने बारे में",
    "TERMS_CONDITIONS_26": "नियम और शर्तें",
    "PRIVACY_PROFILE_27": "गोपनीयता प्रोफाइल",
    "DONE_28": "किया हुआ",
    "DONT_SHOW_AGE_29": "मेरी उम्र न दिखाएं",
    "DONT_SHOW_DISTANCE_30": "मेरी दूरी नहीं दिखाएं",
    "OK_31": "ठीक",
    "CANCEL_32": "रद्द करना",
    "ERROR_OCCURED_33": "त्रुटि हुई",
    "TRY_AGAIN_34": "",
    "PLEASE_WAIT_35": "कृपया प्रतीक्षा करें",
    "CHAT_36": "बातचीत",
    "SEARCH_37": "खोज",
    "MESSAGES_38": "संदेशों",
    "SETTINGS_39": "सेटिंग्स",
    "EARN_T_DOLLARS_40": "टी $ अर्जित करें",
    "LOGOUT_41": "लोग आउट",
    "TUBELY_42": "तुबली",
    "WEBCHAT_43": "वेब चॅट",
    "REPORT_ABUSE_44": "दुरुपयोग होने की सूचना दें",
    "HELP_45": "मदद",
    "ROOMS_46": "कमरा",
    "SPANISH_47": "स्पेनीस",
    "USER_48": "उपयोगकर्ता",
    "DESCRIPTION_49": "विवरण",
    "JOIN_50": "में शामिल होने के",
    "OUT_51": "बाहर",
    "ME_52": "मुझे",
    "NAME_53": "नाम",
    "TIME_IN_54": "समय शुरू",
    "RULES_55": "नियम",
    "_56": "सभी स्पेनीस लोगों का स्वागत है यहाँ",
    "_57": "हिन्दी",
    "_58": "इंडोनेशियाई",
    "_59": "मलेशियाई",
    "_60": "पिनॉय",
    "_61": "तामिल",
    "_62": "तुबली चैट",
    "_63": "यू.के.",
    "_64": "अमेरिका",
    "_65": "बजे",
    "USER_GENDER_66": "लिंग",
    "USER_LOCATION_67": "स्थान",
    "USER_GENDER_FEMALE_68": "महिला",
    "_69": "भीमर डेम",
    "USER_PROFILE_70": "प्रोफाइल",
    "SETTINGS_71": "सेटिंग्स",
    "SEND_72": "भेजना",
    "STYLE_73": "शैली",
    "TYPE_HERE_74": "येथे टाइप करा",
    "TIME_AM_75": "बजे",
    "TIME_PM_76": "पीएम",
    "SEARCH_OR_CHAT_77": "खोज या एक नया चैट शुरू करें",
    "HELLO_78": "हॅलो",
    "TYPE_A_MESSAGE_79": "एक संदेश लिखें",
    "EARN_MONEY_80": "पैसे कमाओ",
    "LOADING_81": "लोड हो रहा है",
    "USERS_82": "उपयोगकर्ताओं",
    "_83": "सभी हिंदी लोगों का स्वागत यहां है",
    "_84": "सभी इंडोनेशियाई लोगों का स्वागत यहां है",
    "_85": "सभी मालाशियन लोगों का स्वागत यहां है",
    "_86": "सभी पिनोय लोग यहां स्वागत करते हैं",
    "_87": "केवल यूके के लोग ही यहां आ सकते हैं",
    "_88": "केवल अमेरिका के लोग यहां आ सकते हैं",
    "ADD_FRIEND_89": "दोस्त जोड़ें",
    "BLOCK_USER_90": "खंड",
    "DOCK_USER_91": "गोदी",
    "USER_DETAILS_92": "विस्तार",
    "USER_GENDER_MALE_93": "नर",
    "USER_CITY_PROFILE_VALUE_94": "मुंबई",
    "_95": "इंडिया",
    "_96": "उपयोगकर्ता आईडी ब्लॉक करें",
    "_97": "उपयोगकर्ता आईडी का मित्र जोड़ें",
    "USER_BANNED_98": "",
    "_99": "",
    "_100": "",
    "_101": "",
    "_102": "",
    "_103": "",
    "_104": "",
    "_105": "",
    "_106": "",
    "_107": "",
    "_108": "",
    "_109": "",
    "_110": "",
    "_111": "",
    "_112": "",
    "_113": "",
    "_114": "",
    "_115": "",
    "_116": "",
    "_117": "",
    "_118": "",
    "_119": "",
    "_120": "",
    "_121": "",
    "_122": "",
    "_123": "",
    "_124": "",
    "_125": "",
    "_126": "",
    "_127": "",
    "_128": "",
    "_129": "",
    "_130": "",
    "_131": "",
    "_132": "",
    "_133": "",
    "_134": "",
    "_135": "",
    "_136": "",
    "_137": "",
    "_138": "",
    "_139": "",
    "_140": "",
    "_141": "",
    "_142": "",
    "_143": "",
    "_144": "",
    "_145": "",
    "_146": "",
    "_147": "",
    "_148": "",
    "_149": "",
    "_150": "",
    "_151": "",
    "_152": "",
    "_153": "",
    "_154": "",
    "_155": ""
  },
  "en": {
    "WELCOME_1": "Welcome To Tubely",
    "ENTER_USERNAME_2": "Enter your username",
    "ENTER_PASSWORD_3": "Enter your password",
    "FIST_NAME_4": "First Name",
    "LAST_NAME_5": "Last Name",
    "DATE_OF_BIRTH_6": "Date of birth",
    "CITY_7": "City",
    "STATE_8": "State",
    "COUNTRY_9": "Country",
    "SUBMIT_10": "Submit",
    "INCORRECT_USERNAME_PASSWORD_11": "Incorrect username/password try again",
    "CONFIRM_PASSWORD_12": "Confirm password",
    "LOGIN_FACEBOOK_13": "Login with facebook / Login with Google",
    "HELP_14": "Help",
    "ACCOUNT_15": "Account",
    "CHOOSE_GENDER_16": "Choose your gender",
    "MALE_17": "Male",
    "FEMALE_18": "Female",
    "OTHER_19": "Other",
    "SETTINGS_20": "Settings",
    "UPDATE_PROFILE_21": "Update Profile",
    "UPLOAD_PHOTO_22": "Upload Photo",
    "EDIT_PROFILE_PHOTO_23": "Edit Profile Photo",
    "SET_PROFILE_PHOTO_24": "Set Profile Photo",
    "ABOUT_YOURSELF_25": "About yourself",
    "TERMS_CONDITIONS_26": "Terms and conditions",
    "PRIVACY_PROFILE_27": "Privacy Profile",
    "DONE_28": "Done",
    "DONT_SHOW_AGE_29": "Don't show my age",
    "DONT_SHOW_DISTANCE_30": "Don't show my distance",
    "OK_31": "OK",
    "CANCEL_32": "Cancel",
    "ERROR_OCCURED_33": "Error happened / error occurred",
    "TRY_AGAIN_34": "Try again ",
    "PLEASE_WAIT_35": "Please Wait",
    "CHAT_36": "chat",
    "SEARCH_37": "search",
    "MESSAGES_38": "messages",
    "SETTINGS_39": "settings",
    "EARN_T_DOLLARS_40": "earnT$",
    "LOGOUT_41": "logout",
    "TUBELY_42": "tubely",
    "WEBCHAT_43": "webchat",
    "REPORT_ABUSE_44": "report abuse",
    "HELP_45": "Help",
    "ROOMS_46": "rooms",
    "SPANISH_47": "espanol",
    "USER_48": "user",
    "DESCRIPTION_49": "description",
    "JOIN_50": "join",
    "OUT_51": "out",
    "ME_52": "me",
    "NAME_53": "name",
    "TIME_IN_54": "time in",
    "RULES_55": "rules",
    "_56": "All espanol people are welcome here",
    "_57": "hindi",
    "_58": "indonesian",
    "_59": "malaysian",
    "_60": "pinoy",
    "_61": "tamil",
    "_62": "tubely chat",
    "_63": "uk",
    "CHAT_ROOM_TITLE_64": "usa",
    "_65": "age",
    "USER_GENDER_66": "gender",
    "USER_LOCATION_67": "location",
    "USER_GENDER_FEMALE_68": "female",
    "_69": "Bhimar The Dem",
    "USER_PROFILE_70": "Profile",
    "SETTINGS_71": "settings",
    "SEND_72": "send",
    "STYLE_73": "style",
    "TYPE_HERE_74": "type here",
    "TIME_AM_75": "am",
    "TIME_PM_76": "pm",
    "SEARCH_OR_CHAT_77": "search or start a new chat",
    "HELLO_78": "hello",
    "TYPE_A_MESSAGE_79": "type a message",
    "EARN_MONEY_80": "earn money",
    "LOADING_81": "loading",
    "USERS_82": "users",
    "_83": "All Hindi people are welcome here",
    "_84": "All Indonesian people are welcome here",
    "_85": "All Malasian people are welcome here",
    "_86": "All pinoy people are welcome here",
    "_87": "Only people of UK can come here",
    "_88": "Only people of USA can come here",
    "ADD_FRIEND_89": "Add friend",
    "BLOCK_USER_90": "block",
    "DOCK_USER_91": "dock",
    "USER_DETAILS_92": "detail",
    "USER_GENDER_MALE_93": "male",
    "USER_CITY_PROFILE_VALUE_94": "mumbai",
    "_95": "india",
    "_96": "Block userid",
    "_97": "Add friend of user id",
    "USER_BANNED_98": "You are banned",
    "_99": "",
    "_100": "",
    "_101": "",
    "_102": "",
    "_103": "",
    "_104": "",
    "_105": "",
    "_106": "",
    "_107": "",
    "_108": "",
    "_109": "",
    "_110": "",
    "_111": "",
    "_112": "",
    "_113": "",
    "_114": "",
    "_115": "",
    "_116": "",
    "_117": "",
    "_118": "",
    "_119": "",
    "_120": "",
    "_121": "",
    "_122": "",
    "_123": "",
    "_124": "",
    "_125": "",
    "_126": "",
    "_127": "",
    "_128": "",
    "_129": "",
    "_130": "",
    "_131": "",
    "_132": "",
    "_133": "",
    "_134": "",
    "_135": "",
    "_136": "",
    "_137": "",
    "_138": "",
    "_139": "",
    "_140": "",
    "_141": "",
    "_142": "",
    "_143": "",
    "_144": "",
    "_145": "",
    "_146": "",
    "_147": "",
    "_148": "",
    "_149": "",
    "_150": "",
    "_151": "",
    "_152": "",
    "_153": "",
    "_154": "",
    "_155": ""
  },
  "ma": {
    "WELCOME_1": "तुबेली मध्ये आपले स्वागत आहे",
    "ENTER_USERNAME_2": "आपले वापरकर्तानाव प्रविष्ट करा",
    "ENTER_PASSWORD_3": "आपला संकेतशब्द प्रविष्ट करा",
    "FIST_NAME_4": "पहिले नाव",
    "LAST_NAME_5": "आडनाव",
    "DATE_OF_BIRTH_6": "जन्म तारीख",
    "CITY_7": "शहर",
    "STATE_8": "राज्य",
    "COUNTRY_9": "देश",
    "SUBMIT_10": "सबमिट करा",
    "INCORRECT_USERNAME_PASSWORD_11": "अयोग्य वापरकर्तानाव / संकेतशब्द",
    "CONFIRM_PASSWORD_12": "पासवर्डची पुष्टी करा",
    "LOGIN_FACEBOOK_13": "फेसबुक सह लॉगिन करा",
    "HELP_14": "मदत",
    "ACCOUNT_15": "खाते",
    "CHOOSE_GENDER_16": "आपले लिंग निवडा",
    "MALE_17": "नर",
    "FEMALE_18": "स्त्री",
    "OTHER_19": "इतर",
    "SETTINGS_20": "सेटिंग्ज",
    "UPDATE_PROFILE_21": "प्रोफाइल अद्यतनित करा",
    "UPLOAD_PHOTO_22": "फोटो अपलोड करा",
    "EDIT_PROFILE_PHOTO_23": "प्रोफाइल फोटो संपादित करा",
    "SET_PROFILE_PHOTO_24": "प्रोफाइल फोटो सेट करा",
    "ABOUT_YOURSELF_25": "स्वत: बद्दल",
    "TERMS_CONDITIONS_26": "नियम आणि अटी",
    "PRIVACY_PROFILE_27": "गोपनीयता प्रोफाइल",
    "DONE_28": "झाले",
    "DONT_SHOW_AGE_29": "माझे वय दाखवू नका",
    "DONT_SHOW_DISTANCE_30": "माझे अंतर दाखवू नका",
    "OK_31": "ठीक आहे",
    "CANCEL_32": "रद्द करा",
    "ERROR_OCCURED_33": "त्रुटी आली",
    "TRY_AGAIN_34": "",
    "PLEASE_WAIT_35": "कृपया थांबा",
    "CHAT_36": "चॅट करा",
    "SEARCH_37": "शोध",
    "MESSAGES_38": "संदेश",
    "SETTINGS_39": "सेटिंग्ज",
    "EARN_T_DOLLARS_40": "टी $ कमवा",
    "LOGOUT_41": "बाहेर पडणे",
    "TUBELY_42": "तुबेली",
    "WEBCHAT_43": "वैब वार्तालाप",
    "REPORT_ABUSE_44": "गैरवर्तनाची तक्रार नोंदवा",
    "HELP_45": "मदत",
    "ROOMS_46": "खोल्या",
    "SPANISH_47": "स्पॅनिश",
    "USER_48": "वापरकर्ता",
    "DESCRIPTION_49": "वर्णन",
    "JOIN_50": "सामील व्हा",
    "OUT_51": "बाहेर",
    "ME_52": "मी",
    "NAME_53": "नाव",
    "TIME_IN_54": "मध्ये वेळ",
    "RULES_55": "नियम",
    "_56": "सर्व स्पॅनिश लोक येथे स्वागत आहे",
    "_57": "हिंदी",
    "_58": "इंडोनेशियाई",
    "_59": "मलेशियाचा",
    "_60": "पिनोय",
    "_61": "तमिळ",
    "_62": "तुबेली चॅट",
    "_63": "यूके",
    "_64": "यूएसए",
    "_65": "दि",
    "USER_GENDER_66": "लिंग",
    "USER_LOCATION_67": "स्थान",
    "USER_GENDER_FEMALE_68": "महिला",
    "_69": "भीमर डेम",
    "USER_PROFILE_70": "प्रोफाइल",
    "SETTINGS_71": "सेटिंग्ज",
    "SEND_72": "पाठवा",
    "STYLE_73": "शैली",
    "TYPE_HERE_74": "यहां टाइप करें",
    "TIME_AM_75": "दि",
    "TIME_PM_76": "सायं",
    "SEARCH_OR_CHAT_77": "शोधा किंवा एक नवीन गप्पा प्रारंभ करा",
    "HELLO_78": "नमस्ते",
    "TYPE_A_MESSAGE_79": "एक संदेश टाइप करा",
    "EARN_MONEY_80": "पैसे कमवा",
    "LOADING_81": "लोडिंग",
    "USERS_82": "वापरकर्ते",
    "_83": "सर्व हिंदी लोक इथे स्वागत आहे",
    "_84": "सर्व इंडोनेशियातील लोकांचे स्वागत आहे येथे",
    "_85": "सर्व मालाशियन लोकांचे इथे स्वागत आहे",
    "_86": "सर्व पिनोळ लोक इथे स्वागत आहे",
    "_87": "फक्त यूकेचे लोक इथे येऊ शकतात",
    "_88": "केवळ अमेरिकेचे लोक इथे येऊ शकतात",
    "ADD_FRIEND_89": "मित्र जोडा",
    "BLOCK_USER_90": "ब्लॉक करा",
    "DOCK_USER_91": "गोदी",
    "USER_DETAILS_92": "तपशील",
    "USER_GENDER_MALE_93": "पुरुष",
    "USER_CITY_PROFILE_VALUE_94": "मुंबई",
    "_95": "भारत",
    "_96": "वापरकर्ता आयडी ब्लॉक करा",
    "_97": "",
    "USER_BANNED_98": "",
    "_99": "",
    "_100": "",
    "_101": "",
    "_102": "",
    "_103": "",
    "_104": "",
    "_105": "",
    "_106": "",
    "_107": "",
    "_108": "",
    "_109": "",
    "_110": "",
    "_111": "",
    "_112": "",
    "_113": "",
    "_114": "",
    "_115": "",
    "_116": "",
    "_117": "",
    "_118": "",
    "_119": "",
    "_120": "",
    "_121": "",
    "_122": "",
    "_123": "",
    "_124": "",
    "_125": "",
    "_126": "",
    "_127": "",
    "_128": "",
    "_129": "",
    "_130": "",
    "_131": "",
    "_132": "",
    "_133": "",
    "_134": "",
    "_135": "",
    "_136": "",
    "_137": "",
    "_138": "",
    "_139": "",
    "_140": "",
    "_141": "",
    "_142": "",
    "_143": "",
    "_144": "",
    "_145": "",
    "_146": "",
    "_147": "",
    "_148": "",
    "_149": "",
    "_150": "",
    "_151": "",
    "_152": "",
    "_153": "",
    "_154": "",
    "_155": ""
  },
  "ta": {
    "WELCOME_1": "ட்யூபிலி உங்களை வரவேற்கிறது ",
    "ENTER_USERNAME_2": "உங்கள் பயனர்பெயரை உள்ளிடவும்",
    "ENTER_PASSWORD_3": "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    "FIST_NAME_4": "முதல் பெயர்",
    "LAST_NAME_5": "கடைசி பெயர்",
    "DATE_OF_BIRTH_6": "பிறந்த தேதி",
    "CITY_7": "",
    "STATE_8": "மாநிலம்",
    "COUNTRY_9": "நாடு",
    "SUBMIT_10": "",
    "INCORRECT_USERNAME_PASSWORD_11": "தவறான பயனர்பெயர் அல்லது கடவுச்சொல்",
    "CONFIRM_PASSWORD_12": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "LOGIN_FACEBOOK_13": "பெய்ஸ்புக் உடன் உள்நுழைக",
    "HELP_14": "உதவி",
    "ACCOUNT_15": "",
    "CHOOSE_GENDER_16": "உங்கள் பாலினத்தைத் தேர்வுசெய்யவும்",
    "MALE_17": "ஆண்",
    "FEMALE_18": "",
    "OTHER_19": "மற்ற",
    "SETTINGS_20": "அமைப்புகள்",
    "UPDATE_PROFILE_21": "சுயவிவரத்தை புதுப்பிக்கவும்",
    "UPLOAD_PHOTO_22": "புகைப்படத்தைப் புதுப்பிக்கவும்",
    "EDIT_PROFILE_PHOTO_23": "சுயவிவர படத்தை திருத்தவும்",
    "SET_PROFILE_PHOTO_24": "சுயவிவர புகைப்படத்தை அமை",
    "ABOUT_YOURSELF_25": "உங்களை பற்றி",
    "TERMS_CONDITIONS_26": "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
    "PRIVACY_PROFILE_27": "தனியுரிமை சுயவிவரம்",
    "DONE_28": "முடிந்தது",
    "DONT_SHOW_AGE_29": "என் வயதை காட்டாதே",
    "DONT_SHOW_DISTANCE_30": "என் தூரம் காட்டாதே",
    "OK_31": "சரி",
    "CANCEL_32": "ரத்து",
    "ERROR_OCCURED_33": "பிழை ஏற்பட்டது",
    "TRY_AGAIN_34": "",
    "PLEASE_WAIT_35": "",
    "CHAT_36": "",
    "SEARCH_37": "",
    "MESSAGES_38": "",
    "SETTINGS_39": "",
    "EARN_T_DOLLARS_40": "",
    "LOGOUT_41": "",
    "TUBELY_42": "",
    "WEBCHAT_43": "",
    "REPORT_ABUSE_44": "",
    "HELP_45": "",
    "ROOMS_46": "",
    "SPANISH_47": "",
    "USER_48": "",
    "DESCRIPTION_49": "",
    "JOIN_50": "",
    "OUT_51": "",
    "ME_52": "",
    "NAME_53": "",
    "TIME_IN_54": "",
    "RULES_55": "",
    "_56": "",
    "_57": "",
    "_58": "",
    "_59": "",
    "_60": "",
    "_61": "",
    "_62": "",
    "_63": "",
    "_64": "",
    "_65": "",
    "USER_GENDER_66": "",
    "USER_LOCATION_67": "",
    "USER_GENDER_FEMALE_68": "",
    "_69": "",
    "USER_PROFILE_70": "",
    "SETTINGS_71": "",
    "SEND_72": "",
    "STYLE_73": "",
    "TYPE_HERE_74": "",
    "TIME_AM_75": "",
    "TIME_PM_76": "",
    "SEARCH_OR_CHAT_77": "",
    "HELLO_78": "",
    "TYPE_A_MESSAGE_79": "",
    "EARN_MONEY_80": "",
    "LOADING_81": "",
    "USERS_82": "",
    "_83": "",
    "_84": "",
    "_85": "",
    "_86": "",
    "_87": "",
    "_88": "",
    "ADD_FRIEND_89": "",
    "BLOCK_USER_90": "",
    "DOCK_USER_91": "",
    "USER_DETAILS_92": "",
    "USER_GENDER_MALE_93": "",
    "USER_CITY_PROFILE_VALUE_94": "",
    "_95": "",
    "_96": "",
    "_97": "",
    "USER_BANNED_98": "",
    "_99": "",
    "_100": "",
    "_101": "",
    "_102": "",
    "_103": "",
    "_104": "",
    "_105": "",
    "_106": "",
    "_107": "",
    "_108": "",
    "_109": "",
    "_110": "",
    "_111": "",
    "_112": "",
    "_113": "",
    "_114": "",
    "_115": "",
    "_116": "",
    "_117": "",
    "_118": "",
    "_119": "",
    "_120": "",
    "_121": "",
    "_122": "",
    "_123": "",
    "_124": "",
    "_125": "",
    "_126": "",
    "_127": "",
    "_128": "",
    "_129": "",
    "_130": "",
    "_131": "",
    "_132": "",
    "_133": "",
    "_134": "",
    "_135": "",
    "_136": "",
    "_137": "",
    "_138": "",
    "_139": "",
    "_140": "",
    "_141": "",
    "_142": "",
    "_143": "",
    "_144": "",
    "_145": "",
    "_146": "",
    "_147": "",
    "_148": "",
    "_149": "",
    "_150": "",
    "_151": "",
    "_152": "",
    "_153": "",
    "_154": "",
    "_155": ""
  }
}